# Specify root directory for monorepo structure
[build]
builder = "nixpacks"
rootDirectory = "server"

[deploy]
startCommand = "python scripts/run_migrations.py && uvicorn src.app:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
